---
- name: config_monit | configuring monit
  template: src=templates/etc/monit/monitrc.j2 dest=/etc/monit/monitrc owner=root group=root mode=0700
  notify: restart monit

- name: config_monit | configuring monitored services
  template: src=templates/etc/monit/conf.d/monitor.j2 dest=/etc/monit/conf.d/{{ item.name }} owner=root group=root mode=0644
  notify: reload monit
  with_items: monit_monitor_services
  when: item.monitored is defined and item.monitored

- name: config_monit | removing unmonitored services
  file: path=/etc/monit/conf.d/{{ item.name }} state=absent
  notify: reload monit
  with_items: monit_monitor_services
  when: item.monitored is defined and not item.monitored


#### Below is for Ansible 2.0 when monit module is available
#    - name: enabling monit monitoring of processes
#      monit: name={{ item.name }} state=monitored
#      with_items: monit_monitor_services
#      when: item.monitored is defined and item.monitored

#    - name: disable monit monitoring of processes
#      monit: name={{ item.name }} state=unmonitored
#      with_items: monit_monitor_services
#      when: item.monitored is defined and not item.monitored
